runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

builtins:
- remote_api: on

# [START env_variables]
env_variables:
  USE_GAE_MEMCACHE: 1
  GOOGLE_APPLICATION_CREDENTIALS: ./khan-cachetest-4e33955967d6.json
  DATASTORE_DATASET: khan-cachetest
  DATASTORE_HOST: http://localhost:8081
  DATASTORE_PROJECT_ID: khan-cachetest
  DATASTORE_USE_PROJECT_ID_AS_APP_ID: true
  # MEMCACHE_SERVER: your-memcache-server
  # If you are using a third-party or self-hosted Memcached server with SASL
  # authentiation enabled, uncomment and fill in these values with your
  # username and password.
  # MEMCACHE_USERNAME: your-memcache-username
  # MEMCACHE_PASSWORD: your-memcache-password
# [END env_variables]
